### ISSUE TITLE
Shape error

### ISSUE THREAD

**Issue by tyleretchart** [jingli9111/GORU-tensorflow#1]
Hey I read your paper and was super interested in trying out the GORU in the charRNN task. However, when I use your code I get this error:

`ValueError: Dimension size must be evenly divisible by 126 but is 6350 for 'RNN/rnn_decoder/rnn_decoder/multi_rnn_cell/cell_0/goru_cell/while/cond/cond/Reshape_2' (op: 'Reshape') with input shapes: [50,127], [3] and with input tensors computed as partial shapes: input[1] = [?,63,2].`

I'm not really sure where this is coming from. Because it is trying to divide 6350 by 126, but the input shape is [50, 127] and 6350 is divisible by 127.

**Comment by indiejoseph** [comment]
+1

**Comment by jingli9111** [comment]
Very sorry for the late reply. I just updated the code and fixed this problem.

The GORU model in default use FFT style orthogonal architecture. If you read my previous paper, you can see this FFT architecture is like a binary tree therefore only support hidden size 2^N.

I updated the code to support all possible hidden state size. 

Thanks!
